Первая функция
htmlacademy-javascript/1734937-keksobooking-24 pull request #3
Opened 2021-09-27 13:31 UTC by Vladlen1777

2021-09-27 17:33 UTC, Dima-Dim requested changes
Убрать дубли функций.
Решить конфиликт с файлом Readme.md (https://github.com/htmlacademy-javascript/1734937-keksobooking-24/pull/3)

2021-09-27 17:33 UTC, Dima-Dim commented on js/main.js
> +function getRandomWhole(min, max) {
Я думаю нам достаточно одной такой функции.
Ещё стоит учесть кртерий https://up.htmlacademy.ru/javascript/24/criteries#d5
Такой вариант объявления может быть не удобнем. Рекомендую обявлять функции через const, тогда вероятность созадать нескольких функций с одинаковыми названиями будет поменьше.

2021-09-28 05:30 UTC, Sergey-Rozhkov commented on Readme.md
> +* Наставник: [Дмитрий Гуляев](https://github.com/Dima-Dim).
Привет, хотел уточнить - почему решил сменить наставника ?

2021-09-28 14:25 UTC, Vladlen1777 commented on Readme.md
> +* Наставник: [Дмитрий Гуляев](https://github.com/Dima-Dim).
добрый день, связаться не получилось. указан только вк и фэйсбук. в вк ответили через большой промежуток времени.

2021-09-28 14:28 UTC, Vladlen1777 commented on js/main.js
> +function getRandomWhole(min, max) {
а как же значение "до" меньшее, чем значение "после"? получается оставляем по одной фунции с целым числом и с запятой?

2021-09-28 15:08 UTC, Dima-Dim approved these changes

2021-09-28 15:19 UTC, Dima-Dim commented on js/main.js
> +function getRandomWhole(min, max) {
А кто там мешает передавать значения в нужном порядке? У нас есть функция, у неё определён интерфейс и в соответствии с ним мы её и будем использовать.

2021-10-01 17:25 UTC, merged